name: SpigotLib
author: gyuriX
version: 8.0.1
api-version: 1.13
main: gyurix.spigotlib.Main
loadbefore: [ProtocolLib,ProtocolSupport]
softdepend: [LilyPad-Connect,ViaVersion,Vault,Essentials,PlaceholderAPI,WorldEdit]
commands:
  spigotlib:
    aliases: [sl]
    description: Main command